name: Daily Newspaper Deploy

on:
  push:
    branches:
      - main
  schedule:
    # 04:10 UTC is 09:40 AM IST
    - cron: '10 4 * * *'
  workflow_dispatch: # Allows you to manually trigger it anytime

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          pip install beautifulsoup4

      - name: Fetch Today's Papers
        run: python fetch_papers.py

      - name: Crop Market Box
        run: |
          pdftocairo -png -f 1 -l 1 -x 25 -y 220 -W 320 -H 250 bs.pdf crop
          mv crop*.png market_box.png

      - name: Commit and Push Changes to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated daily newspaper update"
          branch: main
